# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bqMhYi-M8916KKwdrcWYgkyTuBHcH17M

1.c Suite Fibonnaci :
"""

n = int(input ("Entrer la maximum de la suite:"))
U0 = 0
U1 = 1
#Un = U(n+1) + U(n+2)

for n in range(2,n):
  Un = U0 + U1
  print(Un)
  U0 = U1
  U1 = Un