# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bqMhYi-M8916KKwdrcWYgkyTuBHcH17M

1.a: Fonction polynomiale :
"""

def polynome(x):
  x = int(input())
  resultat = (x**3)-(1.5*x**2)-(6*x)+5
  return resultat 
  print(polynome(x))

polynome(x)