# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQOJ48EL23NkGrfMcg5xxowf-9F7SFtg

2. Gestion des exceptions :
"""

def polynome(x):
    a = 1 
    while a == 1 :
        try :
            x = float(input("x = "))
            if x < 0 :
                print("L'entrée de nombre négatif est interdite")
                break
            if x > 100000000 :
                print("L'entrée de trop grands nombre est interdite")
                break
            if x < 0.0000001 :
                print("L'entréede trop petits nombres est interdite")
                break

            resultat = (x**3)-(1.5*x**2)-(6*x)+5
            return resultat
            a = 2
        except :
            a = 2
            print('Seul les valeurs numériques sont acceptées')
            break
    
    print(polynome(x))

polynome(5)